<a href="https://colab.research.google.com/github/yrsf75h9mk-ctrl/AI-NLP-Study/blob/main/Day%2002_2026/10/01_%EB%B2%A1%ED%84%B0%ED%99%94_%EC%8B%A4%EC%8A%B5%ED%95%98%EA%B8%B01_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise

`벡터화`의 실습 노트북입니다. [[YOUR CODE]]로 표시된 부분을 채워 실습 페이지를 완성해봅시다.

## 라이브러리 소개

`Scikit-learn`에서는 TF-IDF를 쉽게 진행할 수 있는 툴을 제공하고 있습니다.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

먼저 `TfidfTransformer` 사용 방법을 살펴보겠습니다.  

`TfidfTransformer`는 이미 단어 카운트 행렬이 있는 경우 이것을 TF-IDF 행렬로 변환해줍니다.  
여기에서는 `CountVectorizer`로 만들고 `TfidfTransformer`를 써보겠습니다.

In [ ]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

다음은 단어사전입니다.

In [ ]:
vectorizer.get_feature_names_out()

corpus의 각 문서는 위 단어 사전을 기반으로 문서 벡터가 됩니다.  
예를 들어 단어사전이 ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third','this']이고 어떤 문서의 벡터값이 [0, 2, 0, 1, 0, 1, 1, 0, 1]이라면 해당 문서에 'document'는 2회, 'is', 'second', 'the', 'this'는 각각 1회 등장했다는 의미가 됩니다.

In [ ]:
X.toarray()

위 단어 카운트 행렬을 `TfidfTransformer`을 통해 TF-IDF 행렬로 바꿔보겠습니다.

In [ ]:
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
tfidf

In [ ]:
tfidf.toarray()

TF-IDF를 계산하는 공식은 다음과 같습니다.

$$\text{TF-IDF} = TF \times IDF$$

여기에서 TF와 IDF는 다음과 같습니다.  

TF(Term Frequency): 특정 단어(t)가 해당 문서(d)에서 얼마나 자주 등장하는가?

$$TF(t,d)=\frac{\text{특정 단어가 등장한 문서}}{\text{전체 문서의 수}}$$

IDF는 다음과 같습니다.

IDF(Inverse Document Frequency): 특정 단어(t)가 모든 문서에 얼마나 희귀한가?

$$IDF(t) = log\frac{전체 문서의 수}{\text{특정 단어가 등장한 문서} + 1}$$

TF-IDF는 위와 같은 계산을 통해 전체적으로 자주 사용되지 않는데 특정 문서에서 많이 사용되면 더 높은 점수를 부가하게 됩니다. 이를 통해 각 단어가 각 문서에서 얼만큼 중요한지 반영하거나 각 문서의 핵심 단어를 추려낼 수 있습니다.

예를 들어 'This is the first document.' 이 문서에서 'is'와 'first'는 둘 다 1회씩 등장하지만 'is'의 경우 다른 문서에서 자주 등장했기 때문에 상대적으로 중요도가 낮게 측정되고 first는 높게 측정됩니다.

위에서는 이해를 위해 단계를 나누어 구현했지만 `TfidfVectorizer`를 통해 간단히 구현할 수 있습니다.

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

In [ ]:
X.toarray()

## 실습 데이터 소개

이번 실습에서 사용할 데이터는 1789년 조지 워싱턴부터 2017년 도널드 트럼프까지 대통령 취임 연설이 담겨있습니다.

In [24]:
!wget -q https://melaniewalsh.github.io/Intro-Cultural-Analytics/_downloads/64e2547e2d86c20cc2a74f660143cfeb/US_Inaugural_Addresses.zip
!unzip -q /content/US_Inaugural_Addresses.zip

replace __MACOSX/._US_Inaugural_Addresses? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
open("/content/US_Inaugural_Addresses/56_obama_2009.txt").read()

## Q. 각 문서를 TF-IDF로 분석하여 각 문서별로 어떤 단어가 핵심이었는지 분석하십시오.  
다음 링크를 참조하여 진행하여도 좋습니다.[[링크]](https://melaniewalsh.github.io/Intro-Cultural-Analytics/05-Text-Analysis/03-TF-IDF-Scikit-Learn.html)

In [2]:
# [[YOUR CODE]]
#라이브러리 불러오기
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
pd.set_option("display.max_rows", 600)
from pathlib import Path
import glob

In [3]:
from google.colab import files

uploaded = files.upload()

Saving US_Inaugural_Addresses.zip to US_Inaugural_Addresses.zip

In [4]:
import zipfile

with zipfile.ZipFile("US_Inaugural_Addresses.zip", "r") as z:
    z.extractall(".")

In [5]:
import os

print(os.listdir())

['.config', 'US_Inaugural_Addresses.zip', 'US_Inaugural_Addresses', '__MACOSX', 'sample_data']

In [7]:
directory_path = "US_Inaugural_Addresses/"

text_files = glob.glob(f"{directory_path}/*.txt")

text_files

['US_Inaugural_Addresses/33_wilson_1917.txt',
 'US_Inaugural_Addresses/23_hayes_1877.txt',
 'US_Inaugural_Addresses/29_mckinley_1901.txt',
 'US_Inaugural_Addresses/06_madison_1809.txt',
 'US_Inaugural_Addresses/51_bush_george_h_w_1989.txt',
 'US_Inaugural_Addresses/49_reagan_1981.txt',
 'US_Inaugural_Addresses/32_wilson_1913.txt',
 'US_Inaugural_Addresses/42_eisenhower_1953.txt',
 'US_Inaugural_Addresses/13_van_buren_1837.txt',
 'US_Inaugural_Addresses/20_lincoln_1865.txt',
 'US_Inaugural_Addresses/53_clinton_1997.txt',
 'US_Inaugural_Addresses/39_roosevelt_franklin_1941.txt',
 'US_Inaugural_Addresses/24_garfield_1881.txt',
 'US_Inaugural_Addresses/37_roosevelt_franklin_1933.txt',
 'US_Inaugural_Addresses/08_monroe_1817.txt',
 'US_Inaugural_Addresses/14_harrison_1841.txt',
 'US_Inaugural_Addresses/56_obama_2009.txt',
 'US_Inaugural_Addresses/27_cleveland_1893.txt',
 'US_Inaugural_Addresses/05_jefferson_1805.txt',
 'US_Inaugural_Addresses/25_cleveland_1885.txt',
 'US_Inaugural_Addresses/45_johnson_1965.txt',
 'US_Inaugural_Addresses/30_roosevelt_theodore_1905.txt',
 'US_Inaugural_Addresses/28_mckinley_1897.txt',
 'US_Inaugural_Addresses/47_nixon_1973.txt',
 'US_Inaugural_Addresses/16_taylor_1849.txt',
 'US_Inaugural_Addresses/41_truman_1949.txt',
 'US_Inaugural_Addresses/07_madison_1813.txt',
 'US_Inaugural_Addresses/21_grant_1869.txt',
 'US_Inaugural_Addresses/44_kennedy_1961.txt',
 'US_Inaugural_Addresses/38_roosevelt_franklin_1937.txt',
 'US_Inaugural_Addresses/43_eisenhower_1957.txt',
 'US_Inaugural_Addresses/19_lincoln_1861.txt',
 'US_Inaugural_Addresses/17_pierce_1853.txt',
 'US_Inaugural_Addresses/03_adams_john_1797.txt',
 'US_Inaugural_Addresses/22_grant_1873.txt',
 'US_Inaugural_Addresses/57_obama_2013.txt',
 'US_Inaugural_Addresses/34_harding_1921.txt',
 'US_Inaugural_Addresses/52_clinton_1993.txt',
 'US_Inaugural_Addresses/18_buchanan_1857.txt',
 'US_Inaugural_Addresses/09_monroe_1821.txt',
 'US_Inaugural_Addresses/15_polk_1845.txt',
 'US_Inaugural_Addresses/10_adams_john_quincy_1825.txt',
 'US_Inaugural_Addresses/48_carter_1977.txt',
 'US_Inaugural_Addresses/36_hoover_1929.txt',
 'US_Inaugural_Addresses/50_reagan_1985.txt',
 'US_Inaugural_Addresses/46_nixon_1969.txt',
 'US_Inaugural_Addresses/02_washington_1793.txt',
 'US_Inaugural_Addresses/40_roosevelt_franklin_1945.txt',
 'US_Inaugural_Addresses/55_bush_george_w_2005.txt',
 'US_Inaugural_Addresses/26_harrison_1889.txt',
 'US_Inaugural_Addresses/12_jackson_1833.txt',
 'US_Inaugural_Addresses/35_coolidge_1925.txt',
 'US_Inaugural_Addresses/11_jackson_1829.txt',
 'US_Inaugural_Addresses/01_washington_1789.txt',
 'US_Inaugural_Addresses/58_trump_2017.txt',
 'US_Inaugural_Addresses/04_jefferson_1801.txt',
 'US_Inaugural_Addresses/31_taft_1909.txt',
 'US_Inaugural_Addresses/54_bush_george_w_2001.txt']

In [8]:
text_titles = [Path(text).stem for text in text_files]
text_files

['US_Inaugural_Addresses/33_wilson_1917.txt',
 'US_Inaugural_Addresses/23_hayes_1877.txt',
 'US_Inaugural_Addresses/29_mckinley_1901.txt',
 'US_Inaugural_Addresses/06_madison_1809.txt',
 'US_Inaugural_Addresses/51_bush_george_h_w_1989.txt',
 'US_Inaugural_Addresses/49_reagan_1981.txt',
 'US_Inaugural_Addresses/32_wilson_1913.txt',
 'US_Inaugural_Addresses/42_eisenhower_1953.txt',
 'US_Inaugural_Addresses/13_van_buren_1837.txt',
 'US_Inaugural_Addresses/20_lincoln_1865.txt',
 'US_Inaugural_Addresses/53_clinton_1997.txt',
 'US_Inaugural_Addresses/39_roosevelt_franklin_1941.txt',
 'US_Inaugural_Addresses/24_garfield_1881.txt',
 'US_Inaugural_Addresses/37_roosevelt_franklin_1933.txt',
 'US_Inaugural_Addresses/08_monroe_1817.txt',
 'US_Inaugural_Addresses/14_harrison_1841.txt',
 'US_Inaugural_Addresses/56_obama_2009.txt',
 'US_Inaugural_Addresses/27_cleveland_1893.txt',
 'US_Inaugural_Addresses/05_jefferson_1805.txt',
 'US_Inaugural_Addresses/25_cleveland_1885.txt',
 'US_Inaugural_Addresses/45_johnson_1965.txt',
 'US_Inaugural_Addresses/30_roosevelt_theodore_1905.txt',
 'US_Inaugural_Addresses/28_mckinley_1897.txt',
 'US_Inaugural_Addresses/47_nixon_1973.txt',
 'US_Inaugural_Addresses/16_taylor_1849.txt',
 'US_Inaugural_Addresses/41_truman_1949.txt',
 'US_Inaugural_Addresses/07_madison_1813.txt',
 'US_Inaugural_Addresses/21_grant_1869.txt',
 'US_Inaugural_Addresses/44_kennedy_1961.txt',
 'US_Inaugural_Addresses/38_roosevelt_franklin_1937.txt',
 'US_Inaugural_Addresses/43_eisenhower_1957.txt',
 'US_Inaugural_Addresses/19_lincoln_1861.txt',
 'US_Inaugural_Addresses/17_pierce_1853.txt',
 'US_Inaugural_Addresses/03_adams_john_1797.txt',
 'US_Inaugural_Addresses/22_grant_1873.txt',
 'US_Inaugural_Addresses/57_obama_2013.txt',
 'US_Inaugural_Addresses/34_harding_1921.txt',
 'US_Inaugural_Addresses/52_clinton_1993.txt',
 'US_Inaugural_Addresses/18_buchanan_1857.txt',
 'US_Inaugural_Addresses/09_monroe_1821.txt',
 'US_Inaugural_Addresses/15_polk_1845.txt',
 'US_Inaugural_Addresses/10_adams_john_quincy_1825.txt',
 'US_Inaugural_Addresses/48_carter_1977.txt',
 'US_Inaugural_Addresses/36_hoover_1929.txt',
 'US_Inaugural_Addresses/50_reagan_1985.txt',
 'US_Inaugural_Addresses/46_nixon_1969.txt',
 'US_Inaugural_Addresses/02_washington_1793.txt',
 'US_Inaugural_Addresses/40_roosevelt_franklin_1945.txt',
 'US_Inaugural_Addresses/55_bush_george_w_2005.txt',
 'US_Inaugural_Addresses/26_harrison_1889.txt',
 'US_Inaugural_Addresses/12_jackson_1833.txt',
 'US_Inaugural_Addresses/35_coolidge_1925.txt',
 'US_Inaugural_Addresses/11_jackson_1829.txt',
 'US_Inaugural_Addresses/01_washington_1789.txt',
 'US_Inaugural_Addresses/58_trump_2017.txt',
 'US_Inaugural_Addresses/04_jefferson_1801.txt',
 'US_Inaugural_Addresses/31_taft_1909.txt',
 'US_Inaugural_Addresses/54_bush_george_w_2001.txt']

In [9]:
#파일 경로를 입력으로 받아 파일의 영어 텍스트를 읽고, 영어 불용어는 제외한 뒤 TF-IDF 방식으로 벡터화할 준비를 해라
# 1. TF-IDF 벡터화 도구 생성
tfidf_vectorizer = TfidfVectorizer(input='filename', stop_words='english')

#stop_words='english' :불용어(stop words)를 제거하겠다는 의미

In [27]:
#2. 텍스트 파일을 TF-IDF 벡터로 변환
tfidf_vector = tfidf_vectorizer.fit_transform(text_files)

In [11]:
#결과로 나온 tf-idf 벡터를 사용하여 DataFrame을 생성
#"특징 이름" 또는 단어를 열로, 제목을 행으로 설정
tfidf_df = pd.DataFrame(tfidf_vector.toarray(), index=text_titles, columns=tfidf_vectorizer.get_feature_names_out())

In [12]:
#모든 문서에서 단어가 나타나는 횟수를 나타내는 행을 추가
tfidf_df.loc['00_Document Frequency'] = (tfidf_df > 0).sum()

In [13]:
tfidf_slice = tfidf_df[['government', 'borders', 'people', 'obama', 'war', 'honor','foreign', 'men', 'women', 'children']]
tfidf_slice.sort_index().round(decimals=2)

#round(decimals=2): 소수점 둘째 자리까지 반올림

,government,borders,people,obama,war,honor,foreign,men,women,children
00_Document Frequency,53.00,5.00,56.00,3.00,45.00,32.00,32.00,47.00,15.00,22.00
01_washington_1789,0.11,0.00,0.05,0.00,0.00,0.00,0.00,0.02,0.00,0.00
02_washington_1793,0.06,0.00,0.05,0.00,0.00,0.08,0.00,0.00,0.00,0.00
03_adams_john_1797,0.16,0.00,0.19,0.00,0.01,0.10,0.12,0.04,0.00,0.00
04_jefferson_1801,0.16,0.00,0.01,0.00,0.01,0.04,0.00,0.04,0.00,0.00
05_jefferson_1805,0.03,0.00,0.00,0.00,0.04,0.00,0.06,0.01,0.00,0.02
06_madison_1809,0.00,0.00,0.02,0.00,0.02,0.05,0.05,0.00,0.00,0.00
07_madison_1813,0.04,0.00,0.04,0.00,0.25,0.02,0.02,0.00,0.00,0.00
08_monroe_1817,0.17,0.00,0.11,0.00,0.09,0.01,0.10,0.04,0.00,0.00
09_monroe_1821,0.08,0.00,0.06,0.00,0.11,0.02,0.04,0.01,0.00,0.01
10_adams_john_quincy_1825,0.15,0.00,0.06,0.00,0.05,0.01,0.08,0.03,0.00,0.00
11_jackson_1829,0.10,0.00,0.06,0.00,0.02,0.02,0.07,0.02,0.00,0.00
12_jackson_1833,0.21,0.00,0.14,0.00,0.00,0.00,0.02,0.00,0.00,0.00
13_van_buren_1837,0.12,0.00,0.14,0.00,0.02,0.02,0.06,0.02,0.00,0.01
14_harrison_1841,0.14,0.00,0.14,0.00,0.01,0.02,0.03,0.03,0.00,0.00
15_polk_1845,0.26,0.00,0.08,0.00,0.03,0.01,0.09,0.02,0.00,0.01
16_taylor_1849,0.12,0.00,0.05,0.00,0.00,0.02,0.05,0.00,0.00,0.00
17_pierce_1853,0.08,0.00,0.05,0.00,0.00,0.02,0.04,0.01,0.00,0.03
18_buchanan_1857,0.12,0.00,0.11,0.00,0.08,0.01,0.04,0.03,0.00,0.05
19_lincoln_1861,0.12,0.00,0.13,0.00,0.02,0.00,0.02,0.00,0.00,0.00
20_lincoln_1865,0.02,0.00,0.00,0.00,0.27,0.00,0.00,0.04,0.00,0.00
21_grant_1869,0.05,0.00,0.03,0.00,0.02,0.05,0.05,0.02,0.00,0.00
22_grant_1873,0.06,0.00,0.10,0.00,0.05,0.02,0.00,0.00,0.00,0.00
23_hayes_1877,0.17,0.00,0.08,0.00,0.00,0.00,0.04,0.02,0.00,0.00
24_garfield_1881,0.19,0.00,0.16,0.00,0.05,0.00,0.00,0.01,0.00,0.04
25_cleveland_1885,0.21,0.00,0.21,0.00,0.00,0.00,0.05,0.01,0.00,0.00
26_harrison_1889,0.06,0.00,0.17,0.00,0.02,0.03,0.01,0.04,0.00,0.00
27_cleveland_1893,0.15,0.00,0.22,0.00,0.00,0.00,0.00,0.04,0.00,0.00
28_mckinley_1897,0.16,0.00,0.16,0.00,0.05,0.03,0.06,0.02,0.00,0.00
29_mckinley_1901,0.15,0.00,0.12,0.00,0.08,0.04,0.01,0.01,0.00,0.00
30_roosevelt_theodore_1905,0.05,0.00,0.10,0.00,0.00,0.00,0.00,0.08,0.00,0.10
31_taft_1909,0.12,0.00,0.03,0.00,0.03,0.01,0.03,0.03,0.00,0.00
32_wilson_1913,0.11,0.00,0.02,0.00,0.00,0.00,0.00,0.14,0.10,0.06
33_wilson_1917,0.00,0.00,0.08,0.00,0.07,0.00,0.00,0.05,0.00,0.00
34_harding_1921,0.08,0.00,0.05,0.00,0.12,0.00,0.00,0.01,0.00,0.00
35_coolidge_1925,0.10,0.00,0.10,0.00,0.02,0.01,0.02,0.02,0.02,0.00
36_hoover_1929,0.20,0.04,0.10,0.00,0.01,0.00,0.01,0.03,0.03,0.01
37_roosevelt_franklin_1933,0.03,0.00,0.08,0.00,0.02,0.02,0.03,0.02,0.00,0.00
38_roosevelt_franklin_1937,0.18,0.03,0.12,0.00,0.01,0.00,0.00,0.10,0.07,0.02
39_roosevelt_franklin_1941,0.05,0.00,0.08,0.00,0.00,0.00,0.00,0.07,0.03,0.00
40_roosevelt_franklin_1945,0.00,0.00,0.02,0.00,0.05,0.03,0.00,0.10,0.05,0.04
41_truman_1949,0.03,0.00,0.10,0.00,0.02,0.01,0.01,0.06,0.00,0.00
42_eisenhower_1953,0.01,0.00,0.10,0.00,0.04,0.03,0.00,0.07,0.00,0.00
43_eisenhower_1957,0.00,0.00,0.10,0.00,0.01,0.05,0.00,0.07,0.00,0.00
44_kennedy_1961,0.00,0.00,0.01,0.00,0.06,0.00,0.00,0.01,0.00,0.00
45_johnson_1965,0.01,0.00,0.11,0.00,0.01,0.00,0.02,0.03,0.00,0.05
46_nixon_1969,0.05,0.00,0.13,0.00,0.03,0.03,0.00,0.01,0.00,0.00
47_nixon_1973,0.10,0.00,0.06,0.00,0.03,0.01,0.00,0.00,0.00,0.02
48_carter_1977,0.06,0.00,0.08,0.00,0.02,0.00,0.02,0.00,0.00,0.00
49_reagan_1981,0.16,0.00,0.08,0.00,0.01,0.00,0.00,0.02,0.04,0.09
50_reagan_1985,0.16,0.00,0.14,0.00,0.01,0.01,0.00,0.03,0.04,0.00
51_bush_george_h_w_1989,0.05,0.00,0.06,0.00,0.03,0.00,0.01,0.04,0.06,0.07
52_clinton_1993,0.05,0.00,0.13,0.00,0.03,0.00,0.02,0.01,0.02,0.06
53_clinton_1997,0.09,0.00,0.09,0.00,0.01,0.00,0.00,0.00,0.02,0.10
54_bush_george_w_2001,0.05,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.08
55_bush_george_w_2005,0.03,0.06,0.05,0.00,0.00,0.04,0.00,0.02,0.04,0.00
56_obama_2009,0.03,0.03,0.07,0.03,0.02,0.01,0.00,0.04,0.08,0.05
57_obama_2013,0.04,0.00,0.11,0.04,0.04,0.00,0.00,0.04,0.04,0.06
58_trump_2017,0.04,0.11,0.11,0.12,0.00,0.00,0.05,0.03,0.05,0.04

TF-IDF 값에 따른 의미
|     TF-IDF 값 | 의미                                            |
| -----------: | --------------------------------------------- |
|          `0` | 해당 문서에 단어가 없거나 TF-IDF 값이 0                    |
| `0.01 ~ 0.1` | 해당 문서에서 중요도가 낮은 편                             |
|  `0.1 ~ 0.3` | 어느 정도 특징을 나타내는 단어                             |
|     `0.3 이상` | 해당 문서에서 상대적으로 중요한 단어일 가능성이 높음                 |
|       매우 큰 값 | 해당 문서에는 자주 등장하면서 다른 문서에는 상대적으로 드문 단어일 가능성이 높음 |

왜 숫자가 커질까?

TF-IDF는 크게 두 가지를 봅니다.

① TF (Term Frequency)
→ 이 문서에서 그 단어가 얼마나 자주 등장하는가?

② IDF (Inverse Document Frequency)
→ 전체 문서에서 얼마나 드문 단어인가?

그래서:

한 문서에서는 자주 나오지만 전체 문서에서는 드문 단어 → 높은 TF-IDF

In [14]:
#"OO_Document Frequency"는 단지 예시를 위해 사용했던 것이므로 이제 삭제
tfidf_df = tfidf_df.drop('00_Document Frequency', errors='ignore')

#단어들이 열이 아닌 행에 위치하도록
tfidf_df.stack().reset_index()

                      level_0    level_1    0
0              33_wilson_1917        000  0.0
1              33_wilson_1917         03  0.0
2              33_wilson_1917         04  0.0
3              33_wilson_1917         05  0.0
4              33_wilson_1917        100  0.0
...                       ...        ...  ...
521937  54_bush_george_w_2001    zachary  0.0
521938  54_bush_george_w_2001       zeal  0.0
521939  54_bush_george_w_2001    zealous  0.0
521940  54_bush_george_w_2001  zealously  0.0
521941  54_bush_george_w_2001       zone  0.0

[521942 rows x 3 columns]

Warning: total number of rows (521942) exceeds max_rows (20000). Limiting to first (20000) rows.

In [15]:
tfidf_df = tfidf_df.stack().reset_index()

In [16]:
tfidf_df = tfidf_df.rename(columns={0:'tfidf', 'level_0': 'document','level_1': 'term', 'level_2': 'term'})

In [17]:
tfidf_df.sort_values(by=['document','tfidf'], ascending=[True,False]).groupby(['document']).head(10)

                          document            term     tfidf
480654          01_washington_1789      government  0.113681
481055          01_washington_1789       immutable  0.103883
481122          01_washington_1789     impressions  0.103883
483284          01_washington_1789    providential  0.103883
482578          01_washington_1789           ought  0.103728
483298          01_washington_1789          public  0.103102
483064          01_washington_1789         present  0.097516
483336          01_washington_1789  qualifications  0.096372
482758          01_washington_1789      peculiarly  0.090546
477600          01_washington_1789         article  0.085786
413973          02_washington_1793            1793  0.229350
414598          02_washington_1793          arrive  0.229350
422531          02_washington_1793     upbraidings  0.229350
418205          02_washington_1793       incurring  0.208140
422655          02_washington_1793        violated  0.208140
422827          02_washington_1793       willingly  0.208140
418323          02_washington_1793     injunctions  0.193091
418660          02_washington_1793       knowingly  0.193091
420112          02_washington_1793        previous  0.193091
422865          02_washington_1793       witnesses  0.193091
302790          03_adams_john_1797          people  0.191180
300674          03_adams_john_1797      government  0.160937
302928          03_adams_john_1797        pleasing  0.147066
300431          03_adams_john_1797         foreign  0.116874
302325          03_adams_john_1797         nations  0.114480
305680          03_adams_john_1797        virtuous  0.110813
300985          03_adams_john_1797          houses  0.110300
301768          03_adams_john_1797    legislatures  0.110300
298728          03_adams_john_1797    constitution  0.104525
300952          03_adams_john_1797           honor  0.102265
498652           04_jefferson_1801      government  0.155691
501119           04_jefferson_1801       principle  0.130113
499762           04_jefferson_1801             let  0.117970
502011           04_jefferson_1801          safety  0.108427
499958           04_jefferson_1801             man  0.106841
503043           04_jefferson_1801      thousandth  0.104513
498927           04_jefferson_1801          honest  0.101696
498275           04_jefferson_1801          fellow  0.097240
501841           04_jefferson_1801          retire  0.094848
500522           04_jefferson_1801         opinion  0.092587
168333           05_jefferson_1805          public  0.180456
165243           05_jefferson_1805           false  0.135863
169604           05_jefferson_1805           state  0.121514
170822           05_jefferson_1805      whatsoever  0.116886
166858           05_jefferson_1805          limits  0.107085
163354           05_jefferson_1805        citizens  0.106592
168472           05_jefferson_1805          reason  0.104438
163467           05_jefferson_1805        comforts  0.101880
168117           05_jefferson_1805           press  0.101549
165124           05_jefferson_1805        expenses  0.096524
31181              06_madison_1809    improvements  0.152559
27925              06_madison_1809     belligerent  0.123161
33348              06_madison_1809          public  0.122235
32355              06_madison_1809         nations  0.104588
33730              06_madison_1809        rendered  0.101706
27784              06_madison_1809     authorities  0.089155
27795              06_madison_1809           avail  0.089155
30043              06_madison_1809        examples  0.089155
28900              06_madison_1809        councils  0.085894
32560              06_madison_1809            ones  0.085894
242739             07_madison_1813             war  0.254249
235081             07_madison_1813         british  0.222972
239042             07_madison_1813        massacre  0.119009
235184             07_madison_1813        captives  0.108003
235956             07_madison_1813           cruel  0.108003
240155             07_madison_1813       prisoners  0.108003
241076             07_madison_1813          savage  0.108003
236720             07_madison_1813         element  0.085005
236821             07_madison_1813           enemy  0.085005
237960             07_madison_1813       honorable  0.084762
133613              08_monroe_1817          states  0.184195
129693              08_monroe_1817      government  0.174125
129727              08_monroe_1817           great  0.160658
134455              08_monroe_1817           union  0.117193
131809              08_monroe_1817          people  0.112825
134458              08_monroe_1817          united  0.112076
128019              08_monroe_1817         dangers  0.108567
131353              08_monroe_1817           naval  0.104713
129450              08_monroe_1817         foreign  0.103460
132161              08_monroe_1817      principles  0.097766
354702              09_monroe_1821           great  0.173751
358588              09_monroe_1821          states  0.137384
357878              09_monroe_1821         revenue  0.115018
359726              09_monroe_1821             war  0.113785
356711              09_monroe_1821         parties  0.109318
359433              09_monroe_1821          united  0.108029
352465              09_monroe_1821        commerce  0.105001
354413              09_monroe_1821           force  0.102947
354459              09_monroe_1821  fortifications  0.098741
358995              09_monroe_1821            term  0.094808
377428   10_adams_john_quincy_1825           union  0.257335
372666   10_adams_john_quincy_1825      government  0.147726
372601   10_adams_john_quincy_1825         general  0.109221
375928   10_adams_john_quincy_1825          rights  0.096300
371477   10_adams_john_quincy_1825     dissensions  0.095289
375310   10_adams_john_quincy_1825          public  0.094573
370720   10_adams_john_quincy_1825    constitution  0.090300
374760   10_adams_john_quincy_1825           peace  0.088183
370877   10_adams_john_quincy_1825         country  0.086898
374797   10_adams_john_quincy_1825     performance  0.085565
474299             11_jackson_1829          public  0.160747
471591             11_jackson_1829       generally  0.122711
470329             11_jackson_1829      diffidence  0.112691
470088             11_jackson_1829       defending  0.105878
475230             11_jackson_1829           shall  0.104933
474865             11_jackson_1829         revenue  0.102776
476896             11_jackson_1829           worth  0.100312
471655             11_jackson_1829      government  0.099698
471264             11_jackson_1829         federal  0.093100
473992             11_jackson_1829           power  0.092071
458419             12_jackson_1833           union  0.212766
453657             12_jackson_1833      government  0.207559
457577             12_jackson_1833          states  0.141549
455773             12_jackson_1833          people  0.136557
456073             12_jackson_1833    preservation  0.128319
453592             12_jackson_1833         general  0.125422
453042             12_jackson_1833        exercise  0.119275
454195             12_jackson_1833       inculcate  0.116720
456244             12_jackson_1833      proportion  0.116720
455997             12_jackson_1833          powers  0.113757
76419            13_van_buren_1837    institutions  0.186889
77815            13_van_buren_1837          people  0.138465
75699            13_van_buren_1837      government  0.116561
79864            13_van_buren_1837        supposed  0.109949
73910            13_van_buren_1837         country  0.109276
72235            13_van_buren_1837          actual  0.096382
75136            13_van_buren_1837      experience  0.093444
72259            13_van_buren_1837       adherence  0.083833
73631            13_van_buren_1837         conduct  0.081635
77570            13_van_buren_1837        opinions  0.081597
141029            14_harrison_1841           power  0.204207
136746            14_harrison_1841    constitution  0.183336
138071            14_harrison_1841       executive  0.157153
140808            14_harrison_1841          people  0.141584
138692            14_harrison_1841      government  0.141142
141998            14_harrison_1841           roman  0.110538
142612            14_harrison_1841          states  0.108621
136357            14_harrison_1841        citizens  0.105857
136290            14_harrison_1841       character  0.102640
142607            14_harrison_1841           state  0.094976
368429                15_polk_1845           union  0.259054
363667                15_polk_1845      government  0.256967
367587                15_polk_1845          states  0.218122
368015                15_polk_1845           texas  0.199846
366877                15_polk_1845         revenue  0.146541
366007                15_polk_1845          powers  0.124655
366281                15_polk_1845      protection  0.107385
361721                15_polk_1845    constitution  0.106528
364437                15_polk_1845       interests  0.105054
363143                15_polk_1845        extended  0.090179
223258              16_taylor_1849           shall  0.266204
219683              16_taylor_1849      government  0.118031
218640              16_taylor_1849          duties  0.117893
221448              16_taylor_1849          object  0.104293
217666              16_taylor_1849        congress  0.103865
222344              16_taylor_1849          purity  0.101793
224642              16_taylor_1849          vested  0.101793
221082              16_taylor_1849        measures  0.101637
217894              16_taylor_1849         country  0.101169
216313              16_taylor_1849      affections  0.097017
291809              17_pierce_1853          hardly  0.114001
294012              17_pierce_1853           power  0.102456
293983              17_pierce_1853        position  0.086643
289730              17_pierce_1853  constitutional  0.086105
291095              17_pierce_1853          expect  0.084436
291675              17_pierce_1853      government  0.084048
288510              17_pierce_1853        apparent  0.080332
294593              17_pierce_1853        regarded  0.080332
295250              17_pierce_1853           shall  0.079615
292831              17_pierce_1853            like  0.079229
349589            18_buchanan_1857          states  0.208199
343723            18_buchanan_1857    constitution  0.188573
349244            18_buchanan_1857           shall  0.161784
348360            18_buchanan_1857        question  0.157007
350806            18_buchanan_1857          whilst  0.141119
350007            18_buchanan_1857       territory  0.140852
350431            18_buchanan_1857           union  0.126444
345669            18_buchanan_1857      government  0.119554
343652            18_buchanan_1857        congress  0.118357
347785            18_buchanan_1857          people  0.105501
280730             19_lincoln_1861    constitution  0.214478
287438             19_lincoln_1861           union  0.203738
280202             19_lincoln_1861            case  0.152422
286596             19_lincoln_1861          states  0.144861
284173             19_lincoln_1861        minority  0.131514
284792             19_lincoln_1861          people  0.130763
280364             19_lincoln_1861          clause  0.125738
282676             19_lincoln_1861      government  0.123837
286251             19_lincoln_1861           shall  0.123099
283727             19_lincoln_1861             law  0.122872
89756              20_lincoln_1865             war  0.267217
86526              20_lincoln_1865        offenses  0.234524
89904              20_lincoln_1865             woe  0.234524
84682              20_lincoln_1865             god  0.151269
86525              20_lincoln_1865         offense  0.141890
89866              20_lincoln_1865           wills  0.141890
81502              20_lincoln_1865        answered  0.131631
88406              20_lincoln_1865          slaves  0.123674
89460              20_lincoln_1865           union  0.114955
81436              20_lincoln_1865      altogether  0.111675
245565               21_grant_1869          dollar  0.270439
248769               21_grant_1869          paying  0.162263
245028               21_grant_1869            deal  0.152454
250500               21_grant_1869          specie  0.152454
245043               21_grant_1869            debt  0.135097
244891               21_grant_1869         country  0.127604
243295               21_grant_1869       advisable  0.116606
247738               21_grant_1869            laws  0.115834
248771               21_grant_1869        payments  0.108175
248767               21_grant_1869             pay  0.098658
312268               22_grant_1873     proposition  0.187222
308569               22_grant_1873         domingo  0.177516
313057               22_grant_1873           santo  0.177516
314192               22_grant_1873         transit  0.177516
314011               22_grant_1873       territory  0.121158
309159               22_grant_1873   extermination  0.118344
313616               22_grant_1873           steam  0.118344
313968               22_grant_1873       telegraph  0.118344
307884               22_grant_1873         country  0.117529
309152               22_grant_1873       extension  0.116618
10917                23_hayes_1877         country  0.186357
12706                23_hayes_1877      government  0.167722
9911                 23_hayes_1877          behalf  0.128316
15350                23_hayes_1877          public  0.123944
14987                23_hayes_1877       political  0.121034
16626                23_hayes_1877          states  0.113587
14756                23_hayes_1877           party  0.112549
11504                23_hayes_1877         dispute  0.112503
14749                23_hayes_1877         parties  0.109554
15604                23_hayes_1877          reform  0.104365
111695            24_garfield_1881      government  0.186855
113811            24_garfield_1881          people  0.162132
109749            24_garfield_1881    constitution  0.158292
115615            24_garfield_1881          states  0.135047
116457            24_garfield_1881           union  0.132321
115798            24_garfield_1881        suffrage  0.119992
113388            24_garfield_1881           negro  0.118782
108776            24_garfield_1881       authority  0.117232
109678            24_garfield_1881        congress  0.112598
112746            24_garfield_1881             law  0.103639
176804           25_cleveland_1885          people  0.210468
174688           25_cleveland_1885      government  0.209164
176732           25_cleveland_1885        partisan  0.169436
177332           25_cleveland_1885          public  0.163662
178263           25_cleveland_1885           shall  0.129498
172742           25_cleveland_1885    constitution  0.127856
175458           25_cleveland_1885       interests  0.118207
174185           25_cleveland_1885    extravagance  0.111416
172351           25_cleveland_1885         citizen  0.102825
178696           25_cleveland_1885          strife  0.101661
446774            26_harrison_1889          people  0.172358
445716            26_harrison_1889            laws  0.154418
448578            26_harrison_1889          states  0.138614
441797            26_harrison_1889          ballot  0.137159
447302            26_harrison_1889          public  0.128566
446112            26_harrison_1889         methods  0.119162
448233            26_harrison_1889           shall  0.118483
444520            26_harrison_1889        friendly  0.104267
443961            26_harrison_1889        european  0.103349
442712            26_harrison_1889    constitution  0.089360
158806           27_cleveland_1893          people  0.221563
156690           27_cleveland_1893      government  0.148364
156565           27_cleveland_1893       frugality  0.128050
159334           27_cleveland_1893          public  0.102520
160235           27_cleveland_1893         service  0.101813
160849           27_cleveland_1893         support  0.099946
153445           27_cleveland_1893        american  0.097267
153224           27_cleveland_1893        activity  0.095964
156691           27_cleveland_1893    governmental  0.095964
154902           27_cleveland_1893      countrymen  0.088564
199668            28_mckinley_1897        congress  0.188773
204895            28_mckinley_1897         revenue  0.168489
203801            28_mckinley_1897          people  0.161797
201685            28_mckinley_1897      government  0.156633
202877            28_mckinley_1897           loans  0.149356
202775            28_mckinley_1897     legislation  0.126367
204329            28_mckinley_1897          public  0.107057
199132            28_mckinley_1897        business  0.106759
201719            28_mckinley_1897           great  0.105322
204909            28_mckinley_1897        revision  0.099571
22594             29_mckinley_1901         islands  0.216480
19987             29_mckinley_1901            cuba  0.206329
21705             29_mckinley_1901      government  0.153681
21084             29_mckinley_1901       executive  0.147843
22352             29_mckinley_1901     inhabitants  0.147374
19688             29_mckinley_1901        congress  0.141999
23821             29_mckinley_1901          people  0.116839
25625             29_mckinley_1901          states  0.102186
26470             29_mckinley_1901          united  0.100439
24097             29_mckinley_1901     preparation  0.097925
195607  30_roosevelt_theodore_1905         regards  0.199163
195174  30_roosevelt_theodore_1905        problems  0.182463
196955  30_roosevelt_theodore_1905           tasks  0.150068
189597  30_roosevelt_theodore_1905          aright  0.146306
195762  30_roosevelt_theodore_1905        republic  0.121428
193825  30_roosevelt_theodore_1905            life  0.118701
190227  30_roosevelt_theodore_1905           cause  0.116483
192196  30_roosevelt_theodore_1905           faced  0.115730
190616  30_roosevelt_theodore_1905      conditions  0.115373
197874  30_roosevelt_theodore_1905            wish  0.106771
508445                31_taft_1909      interstate  0.206957
505098                31_taft_1909        business  0.201378
511914                31_taft_1909          tariff  0.154802
509344                31_taft_1909           negro  0.153669
511443                31_taft_1909           south  0.129384
507651                31_taft_1909      government  0.121451
510230                31_taft_1909          proper  0.114684
510355                31_taft_1909            race  0.113413
507266                31_taft_1909         feeling  0.111255
505130                31_taft_1909           canal  0.110879
57735               32_wilson_1913           great  0.158659
59125               32_wilson_1913             men  0.142924
57261               32_wilson_1913        familiar  0.141669
61667               32_wilson_1913         stirred  0.141669
61734               32_wilson_1913         studied  0.141669
62071               32_wilson_1913          things  0.123915
58660               32_wilson_1913         justice  0.105759
57701               32_wilson_1913      government  0.105520
58840               32_wilson_1913            life  0.102168
58917               32_wilson_1913            look  0.100095
8896                33_wilson_1917          wished  0.228593
1904                33_wilson_1917         counsel  0.174639
6371                33_wilson_1917         purpose  0.152933
235                 33_wilson_1917          action  0.149960
7282                33_wilson_1917           shall  0.134404
8091                33_wilson_1917         thought  0.126568

In [18]:
top_tfidf = tfidf_df.sort_values(by=['document','tfidf'], ascending=[True,False]).groupby(['document']).head(10)

In [19]:
#특정 단어나 문서 확대
top_tfidf[top_tfidf['term'].str.contains('women')]

             document   term     tfidf
152900  56_obama_2009  women  0.084859

In [20]:
top_tfidf[top_tfidf['document'].str.contains('obama')]

             document        term     tfidf
144445  56_obama_2009     america  0.148351
149337  56_obama_2009      nation  0.120229
149397  56_obama_2009         new  0.118002
152132  56_obama_2009       today  0.114792
147629  56_obama_2009  generation  0.100654
148801  56_obama_2009         let  0.091100
148617  56_obama_2009        jobs  0.090727
145950  56_obama_2009      crisis  0.087235
147818  56_obama_2009        hard  0.084859
152900  56_obama_2009       women  0.084859
319606  57_obama_2013     journey  0.167591
316920  57_obama_2013       creed  0.139659
318610  57_obama_2013  generation  0.127260
315426  57_obama_2013     america  0.125044
316530  57_obama_2013    complete  0.114891
321762  57_obama_2013    requires  0.114891
320788  57_obama_2013      people  0.110351
323099  57_obama_2013        time  0.105563
323113  57_obama_2013       today  0.103668
317991  57_obama_2013     evident  0.100896

In [21]:
top_tfidf[top_tfidf['document'].str.contains('trump')]

             document       term     tfidf
486407  58_trump_2017    america  0.350162
488588  58_trump_2017     dreams  0.156436
486408  58_trump_2017   american  0.149226
490579  58_trump_2017       jobs  0.142766
492265  58_trump_2017  protected  0.132439
491412  58_trump_2017      obama  0.120288
491769  58_trump_2017     people  0.112370
494004  58_trump_2017      thank  0.109171
486992  58_trump_2017    borders  0.107075
494599  58_trump_2017         ve  0.107075

In [22]:
#시각화
!pip install altair

Requirement already satisfied: altair in /usr/local/lib/python3.13/dist-packages (5.5.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair) (2.26.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from altair) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from altair) (4.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair) (2026.6.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair) (3.0.3)

In [23]:
#각 대통령별로 TF-IDF 점수가 가장 높은 단어를 보여주는 히트맵을 만들고
#관심 있는 두 단어인 "전쟁"과 "평화" 옆에 빨간 점을 찍어 보겠습니다.

import altair as alt
import numpy as np

# Terms in this list will get a red dot in the visualization
term_list = ['war', 'peace']

# adding a little randomness to break ties in term ranking
top_tfidf_plusRand = top_tfidf.copy()
top_tfidf_plusRand['tfidf'] = top_tfidf_plusRand['tfidf'] + np.random.rand(top_tfidf.shape[0])*0.0001

# base for all visualizations, with rank calculation
base = alt.Chart(top_tfidf_plusRand).encode(
    x = 'rank:O',
    y = 'document:N'
).transform_window(
    rank = "rank()",
    sort = [alt.SortField("tfidf", order="descending")],
    groupby = ["document"],
)

# heatmap specification
heatmap = base.mark_rect().encode(
    color = 'tfidf:Q'
)

# red circle over terms in above list
circle = base.mark_circle(size=100).encode(
    color = alt.condition(
        alt.FieldOneOfPredicate(field='term', oneOf=term_list),
        alt.value('red'),
        alt.value('#FFFFFF00')
    )
)

# text labels, white for darker heatmap colors
text = base.mark_text(baseline='middle').encode(
    text = 'term:N',
    color = alt.condition(alt.datum.tfidf >= 0.23, alt.value('white'), alt.value('black'))
)

# display the three superimposed visualizations
(heatmap + circle + text).properties(width = 600)

alt.LayerChart(...)

1. TF-IDF 점수와 원시 단어 빈도수의 차이점은 무엇인가요?

-> 원시단어빈도수는 단어의 등장 횟수를 나타내지만, tf-idf는 해당 문서에서의 반도와 전체 문서에서의 희소성을 함께 고려하여 단어의 상대적인 중요도를 나타낸다.


2. 위 데이터프레임을 바탕으로, tf-idf 점수에서 발견할 수 있는 잠재적인 문제점이나 한계점은 무엇입니까?

-> 모든 문서에서 공통적으로 언급하는 단어가 중요한 단어일 수 있지만, 문서간 구별력이 낮아 tf-idf 점수가 낮아질 수 있다.


3. TF-IDF 점수를 이용해 분석하면 흥미로울 만한 다른 텍스트 모음은 무엇이라고 생각하시나요? 그 이유는 무엇인가요?

-> 고객 리뷰 데이터를 분석해보면 흥미로울 것 같다. 많은 고객들이 공통적으로 사용하는 단어뿐만 아니라 특정 고객이나 일부 리뷰에서만 나타나는 단어를 찾을 수 있다. 일반적인 의견에서는 드러나지 않는 특이한 불만이나 요구사항을 발견하는 데 활용할 수 있을 것 같다.